component: website
name: website-FG8eVNQeY
org: '1256650399'
app: gzx65536
stage: dev
inputs:
  src:
    src: ./
    index: index.html
    error: index.html
  region: ap-guangzhou
  bucketName: my-bucket
  protocol: http
  isAutoCiDeploy: false
